name: Test on development

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
    with:
      environment: development