name: Export google ads api version

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string
    outputs:
      google-ads-api-version:
        description: 'The google ads api version to use'
        value: ${{ jobs.export-google-ads-api-version.outputs.GOOGLE_ADS_API_VERSION }}

jobs:
  export-google-ads-api-version:
    name: Export google ads api version
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      GOOGLE_ADS_API_VERSION: ${{ steps.export.outputs.GOOGLE_ADS_API_VERSION }}
    steps:
      - name: Export google ads api version
        id: export
        run: |
          echo "GOOGLE_ADS_API_VERSION=${{ vars.GOOGLE_ADS_API_VERSION }}" >> $GITHUB_OUTPUT