name: Test on production

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
    with:
      environment: production

  cleanup:
    name: Cleanup
    needs: test
    uses: ./.github/workflows/cleanup.yml
    with:
      environment: production