name: Test on production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/template.yml
    with:
      environment: production

  release:
    needs: test
    name: Release
    runs-on: ubuntu-latest
    environment: production
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Install Protoc
        run: sudo apt install protobuf-compiler

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --prefer-offline

      - name: Generate google ads api from protos
        run: yarn generate ${{ vars.GOOGLE_ADS_API_VERSION }}

      - name: Build
        run: yarn build

      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}