name: Publish to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  export-google-ads-api-version:
    uses: ./.github/workflows/export-google-ads-api-version.yml
    with:
      environment: production

  build:
    name: Build
    needs: export-google-ads-api-version
    uses: ./.github/workflows/template.yml
    with:
      node-version: 18
      google-ads-api-version: ${{ needs.export-google-ads-api-version.outputs.google-ads-api-version }}
      test: false
      build: true

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    environment: production
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build 18
          path: build

      - name: Publish
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: true
          workspace: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

  cleanup:
    name: Cleanup
    needs: publish
    uses: ./.github/workflows/cleanup.yml
    with:
      environment: production
