name: Publish to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  export-google-ads-api-version:
    uses: ./.github/workflows/export-google-ads-api-version.yml
    with:
      environment: production

  build:
    name: Build
    needs: export-google-ads-api-version
    uses: ./.github/workflows/template.yml
    with:
      node-version: 18
      google-ads-api-version: ${{ needs.export-google-ads-api-version.outputs.google-ads-api-version }}
      test: false
      build: true

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    environment: production
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build 18
          path: build

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      # get version from tag name (e.g. v1.2.3 -> 1.2.3)
      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Print version
        run: echo ${{ steps.version.outputs.VERSION }}

      # - name: Publish
      #   run: npm publish
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')

  cleanup:
    name: Cleanup
    needs: publish
    uses: ./.github/workflows/cleanup.yml
    with:
      environment: production
