name: Generate google ads api and run tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string

jobs:
  test:
    name: Node ${{ matrix.node }} testing
    strategy:
      matrix:
        node: [14, 16, 18]
    uses: ./.github/workflows/template.yml
    with:
      environment: ${{ inputs.environment }}
      node-version: ${{ matrix.node }}
      google-ads-api-version: ${{ vars.GOOGLE_ADS_API_VERSION }}
      test: true

  coveralls:
    name: Coveralls finished
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls finished
        uses: pmienk/coveralls-github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true